# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Download this notebook for our code-along:

From our class GitHub repository "notebooks" directory, download the file "02_numpy_and_pandas.ipynb".  Move this to a convenient place where you are grouping your class related materials.


# Introduction to Numpy ("num-pi")

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why use the Numpy package for Data?
    * It makes our data science life easier!!
        * Numpy brings *decades* of C math into Python!
        * Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
        * NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [52]:
## from numpy import * #Load all the numpy packages
%matplotlib inline
import numpy as np



### A Note About "import as"

    import * 
This loads all submodules. Note: this is a waste of memory when incorporated into deployed code. 
We'll use it here by example - it's fine to use for learning purposes and legibility.

As we'll see later, the proper convention is to use:

    import numpy as np
    
And then to specifically call needed methods:

![](https://www.evernote.com/shard/s97/sh/7b2e1c08-16c3-4cef-9d9d-b329c3559972/b0e9440ee858b94049b37b0308afd2eb/deep/0/lec_03_numpy_and_pandas_draft.png)

### Creating ndarrays

An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [53]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))
d = np.arange(0,11,1)

What are these functions?

    arange?

In [54]:
# Note the way each array is printed:
print("a: ",a)
print("b: ",b)
print("c: ",c)
print("d: ",d)

('a: ', array([ 0.,  0.,  0.]))
('b: ', array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]]))
('c: ', array([[[5, 8, 3, 3],
        [6, 9, 7, 6],
        [2, 1, 5, 5]],

       [[3, 8, 8, 2],
        [6, 1, 4, 3],
        [8, 4, 9, 4]]]))
('d: ', array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))


In [55]:
## Arithmetic in arrays is element wise

In [56]:
>>> a = np.array( [20,30,40,50] )
>>> b = np.arange( 4 )
>>> b

array([0, 1, 2, 3])

In [57]:
>>> c = a-b
>>> c

array([20, 29, 38, 47])

In [58]:
>>> b**2

array([0, 1, 4, 9])

## Indexing, Slicing and Iterating

In [59]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [60]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [61]:
a[2:5]

array([ 4,  9, 16])

In [62]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [63]:
b = np.random.randint(1,100,(4,4))

In [64]:
b

array([[25, 89, 81, 71],
       [ 5,  5, 11, 58],
       [47, 59, 76, 98],
       [90, 22, 20, 25]])

In [65]:
# Guess the output
print(b[2,3])


98


In [66]:
# Guess the output
print(b[0,0])


25


In [67]:
# Guess the output
b[0:3,1]

array([89,  5, 59])

In [68]:
#Guess the output
b[:,1]

array([89,  5, 59, 22])

In [69]:
#Guess the output
b[1:3,:]

array([[ 5,  5, 11, 58],
       [47, 59, 76, 98]])

# Introduction to Pandas

**Pandas, Know it! Love it! We will use it extensively.**

Will allow us to use short lines of code to do important manipulation and viewing of our data
* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting
* i/o
 

_pandas.pydata.org_

## Pandas Overview

_Source: [pandas.pydata.org](http://pandas.pydata.org/pandas-docs/stable/10min.html)_

In [70]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [71]:
dates = pd.date_range('20140101',periods=6)
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [72]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns

Index([u'A', u'B', u'C', u'D'], dtype='object')

In [73]:
# Index, columns, underlying numpy data
df

A         B         C         D
2014-01-01  1.312591 -1.164296 -0.929280  0.230450
2014-01-02  0.849461 -0.668135 -0.565925 -1.033096
2014-01-03 -0.484273 -0.441717  0.606338  0.845852
2014-01-04  0.183280  1.296144  0.302670 -0.251709
2014-01-05  1.427229 -0.517208  0.802216 -1.636764
2014-01-06  0.844124 -1.707452 -0.449785  0.403605

In [74]:
df.T


2014-01-01  2014-01-02  2014-01-03  2014-01-04  2014-01-05  2014-01-06
A    1.312591    0.849461   -0.484273    0.183280    1.427229    0.844124
B   -1.164296   -0.668135   -0.441717    1.296144   -0.517208   -1.707452
C   -0.929280   -0.565925    0.606338    0.302670    0.802216   -0.449785
D    0.230450   -1.033096    0.845852   -0.251709   -1.636764    0.403605

In [75]:
df

A         B         C         D
2014-01-01  1.312591 -1.164296 -0.929280  0.230450
2014-01-02  0.849461 -0.668135 -0.565925 -1.033096
2014-01-03 -0.484273 -0.441717  0.606338  0.845852
2014-01-04  0.183280  1.296144  0.302670 -0.251709
2014-01-05  1.427229 -0.517208  0.802216 -1.636764
2014-01-06  0.844124 -1.707452 -0.449785  0.403605

In [76]:
temp = df.T
temp

2014-01-01  2014-01-02  2014-01-03  2014-01-04  2014-01-05  2014-01-06
A    1.312591    0.849461   -0.484273    0.183280    1.427229    0.844124
B   -1.164296   -0.668135   -0.441717    1.296144   -0.517208   -1.707452
C   -0.929280   -0.565925    0.606338    0.302670    0.802216   -0.449785
D    0.230450   -1.033096    0.845852   -0.251709   -1.636764    0.403605

In [77]:
df = df.T
df

2014-01-01  2014-01-02  2014-01-03  2014-01-04  2014-01-05  2014-01-06
A    1.312591    0.849461   -0.484273    0.183280    1.427229    0.844124
B   -1.164296   -0.668135   -0.441717    1.296144   -0.517208   -1.707452
C   -0.929280   -0.565925    0.606338    0.302670    0.802216   -0.449785
D    0.230450   -1.033096    0.845852   -0.251709   -1.636764    0.403605

In [78]:
df2 = pd.DataFrame({ 'A' : 1.,
                         'B' : pd.Timestamp('20130102'),
                         'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'D' : np.array([3] * 4,dtype='int32'),
                         'E' : 'foo' })
    

df2

A          B    C  D    E
0  1.0 2013-01-02  1.0  3  foo
1  1.0 2013-01-02  1.0  3  foo
2  1.0 2013-01-02  1.0  3  foo
3  1.0 2013-01-02  1.0  3  foo

In [79]:
# With specific dtypes
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

#### Viewing Data

In [80]:
df = df.T
df

A         B         C         D
2014-01-01  1.312591 -1.164296 -0.929280  0.230450
2014-01-02  0.849461 -0.668135 -0.565925 -1.033096
2014-01-03 -0.484273 -0.441717  0.606338  0.845852
2014-01-04  0.183280  1.296144  0.302670 -0.251709
2014-01-05  1.427229 -0.517208  0.802216 -1.636764
2014-01-06  0.844124 -1.707452 -0.449785  0.403605

In [81]:
df.head()


A         B         C         D
2014-01-01  1.312591 -1.164296 -0.929280  0.230450
2014-01-02  0.849461 -0.668135 -0.565925 -1.033096
2014-01-03 -0.484273 -0.441717  0.606338  0.845852
2014-01-04  0.183280  1.296144  0.302670 -0.251709
2014-01-05  1.427229 -0.517208  0.802216 -1.636764

In [82]:
df.tail()

A         B         C         D
2014-01-02  0.849461 -0.668135 -0.565925 -1.033096
2014-01-03 -0.484273 -0.441717  0.606338  0.845852
2014-01-04  0.183280  1.296144  0.302670 -0.251709
2014-01-05  1.427229 -0.517208  0.802216 -1.636764
2014-01-06  0.844124 -1.707452 -0.449785  0.403605

In [83]:
df.index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [84]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.688735 -0.533777 -0.038961 -0.240277
std    0.723323  1.014937  0.704250  0.937519
min   -0.484273 -1.707452 -0.929280 -1.636764
25%    0.348491 -1.040256 -0.536890 -0.837749
50%    0.846793 -0.592672 -0.073557 -0.010629
75%    1.196809 -0.460590  0.530421  0.360316
max    1.427229  1.296144  0.802216  0.845852

In [85]:
df

A         B         C         D
2014-01-01  1.312591 -1.164296 -0.929280  0.230450
2014-01-02  0.849461 -0.668135 -0.565925 -1.033096
2014-01-03 -0.484273 -0.441717  0.606338  0.845852
2014-01-04  0.183280  1.296144  0.302670 -0.251709
2014-01-05  1.427229 -0.517208  0.802216 -1.636764
2014-01-06  0.844124 -1.707452 -0.449785  0.403605

In [86]:
z= df.sort_values(by="B")
z

A         B         C         D
2014-01-06  0.844124 -1.707452 -0.449785  0.403605
2014-01-01  1.312591 -1.164296 -0.929280  0.230450
2014-01-02  0.849461 -0.668135 -0.565925 -1.033096
2014-01-05  1.427229 -0.517208  0.802216 -1.636764
2014-01-03 -0.484273 -0.441717  0.606338  0.845852
2014-01-04  0.183280  1.296144  0.302670 -0.251709

### Selection

In [87]:
df[['A','B']]

A         B
2014-01-01  1.312591 -1.164296
2014-01-02  0.849461 -0.668135
2014-01-03 -0.484273 -0.441717
2014-01-04  0.183280  1.296144
2014-01-05  1.427229 -0.517208
2014-01-06  0.844124 -1.707452

In [88]:
df[0:3]

A         B         C         D
2014-01-01  1.312591 -1.164296 -0.929280  0.230450
2014-01-02  0.849461 -0.668135 -0.565925 -1.033096
2014-01-03 -0.484273 -0.441717  0.606338  0.845852

In [89]:
# By label
df.loc[dates[0]]

A    1.312591
B   -1.164296
C   -0.929280
D    0.230450
Name: 2014-01-01 00:00:00, dtype: float64

In [94]:
# multi-axis by label
df.loc[:,['A','B']]

A         B
2014-01-01  1.312591 -1.164296
2014-01-02  0.849461 -0.668135
2014-01-03 -0.484273 -0.441717
2014-01-04  0.183280  1.296144
2014-01-05  1.427229 -0.517208
2014-01-06  0.844124 -1.707452

In [91]:
# Date Range
df.loc['20140102':'20140104',['B']]

B
2014-01-02 -0.668135
2014-01-03 -0.441717
2014-01-04  1.296144

In [95]:
# Fast access to scalar
df.at[dates[1],'B']

-0.66813523416084142

### Operations

In [96]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.688735 -0.533777 -0.038961 -0.240277
std    0.723323  1.014937  0.704250  0.937519
min   -0.484273 -1.707452 -0.929280 -1.636764
25%    0.348491 -1.040256 -0.536890 -0.837749
50%    0.846793 -0.592672 -0.073557 -0.010629
75%    1.196809 -0.460590  0.530421  0.360316
max    1.427229  1.296144  0.802216  0.845852

In [99]:
df.mean(),df.mean(1) # Operation on two different axes
# there are pandas' methods for min, max etc. as well

(A    0.688735
 B   -0.533777
 C   -0.038961
 D   -0.240277
 dtype: float64, 2014-01-01   -0.137634
 2014-01-02   -0.354424
 2014-01-03    0.131550
 2014-01-04    0.382597
 2014-01-05    0.018868
 2014-01-06   -0.227377
 Freq: D, dtype: float64)

### Boolean Indexing

In [100]:
df

A         B         C         D
2014-01-01  1.312591 -1.164296 -0.929280  0.230450
2014-01-02  0.849461 -0.668135 -0.565925 -1.033096
2014-01-03 -0.484273 -0.441717  0.606338  0.845852
2014-01-04  0.183280  1.296144  0.302670 -0.251709
2014-01-05  1.427229 -0.517208  0.802216 -1.636764
2014-01-06  0.844124 -1.707452 -0.449785  0.403605

In [101]:
df[df.A < 0] # Basically a 'where' operation

A         B         C         D
2014-01-03 -0.484273 -0.441717  0.606338  0.845852

In [103]:
df

A         B         C         D
2014-01-01  1.312591 -1.164296 -0.929280  0.230450
2014-01-02  0.849461 -0.668135 -0.565925 -1.033096
2014-01-03 -0.484273 -0.441717  0.606338  0.845852
2014-01-04  0.183280  1.296144  0.302670 -0.251709
2014-01-05  1.427229 -0.517208  0.802216 -1.636764
2014-01-06  0.844124 -1.707452 -0.449785  0.403605

In [102]:
df.A < 0

2014-01-01    False
2014-01-02    False
2014-01-03     True
2014-01-04    False
2014-01-05    False
2014-01-06    False
Freq: D, Name: A, dtype: bool

In [104]:
# Two conditions added together
df[(df.A < 0) & (df.B > .5) ]

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [105]:
# Two conditions ORed together
df[(df.A < -1) | (df.D > 0)]

A         B         C         D
2014-01-01  1.312591 -1.164296 -0.929280  0.230450
2014-01-03 -0.484273 -0.441717  0.606338  0.845852
2014-01-06  0.844124 -1.707452 -0.449785  0.403605

### Merge

In [106]:
np.random.randn(10,4)

array([[ 1.72250527, -1.39860791,  0.23003156,  0.14822498],
       [-1.09445454,  0.83836821,  0.5559105 ,  0.22270958],
       [-0.56935767,  0.73234573, -0.31209575, -1.15474713],
       [ 1.27342558,  0.34125228,  0.00744492,  0.07078684],
       [-0.26223157,  0.08091813, -0.80655897,  1.73189061],
       [-1.19019231, -1.76136502,  0.64051943, -0.55184501],
       [-0.52225793, -2.57781335,  0.7941154 ,  0.01787995],
       [ 0.66113877, -1.30534824,  1.43924803, -0.0163174 ],
       [-0.11825385,  0.31959699,  0.46074827,  0.23982667],
       [-0.41698594,  1.20025461,  0.53804591, -1.08809426]])

In [107]:
##Concatenating pandas objects together
# create a dataframe to use as an example
df2 = pd.DataFrame(np.random.randn(10,4))
df2

0         1         2         3
0 -0.547021 -2.570554 -1.319725 -1.081451
1 -2.795829 -1.088756 -0.660330  0.162107
2  0.342878  1.233027  0.656818 -1.415270
3 -0.154186  0.050133  0.298461 -0.668897
4  1.162890 -1.206511  0.950059 -0.119503
5 -0.243244 -0.014210  0.691176  0.792504
6  0.347263  0.878205  0.070437  2.126217
7  0.293059  0.271851  0.352356  0.737672
8  0.898070 -0.978699 -0.675076 -0.977196
9 -0.377312 -0.102855  1.256755  1.984360

In [108]:
# Break it into pieces
pieces = [df2[:3], df2[3:7],df2[7:]]
pieces

[          0         1         2         3
 0 -0.547021 -2.570554 -1.319725 -1.081451
 1 -2.795829 -1.088756 -0.660330  0.162107
 2  0.342878  1.233027  0.656818 -1.415270,
           0         1         2         3
 3 -0.154186  0.050133  0.298461 -0.668897
 4  1.162890 -1.206511  0.950059 -0.119503
 5 -0.243244 -0.014210  0.691176  0.792504
 6  0.347263  0.878205  0.070437  2.126217,
           0         1         2         3
 7  0.293059  0.271851  0.352356  0.737672
 8  0.898070 -0.978699 -0.675076 -0.977196
 9 -0.377312 -0.102855  1.256755  1.984360]

In [109]:
pd.concat(pieces)

0         1         2         3
0 -0.547021 -2.570554 -1.319725 -1.081451
1 -2.795829 -1.088756 -0.660330  0.162107
2  0.342878  1.233027  0.656818 -1.415270
3 -0.154186  0.050133  0.298461 -0.668897
4  1.162890 -1.206511  0.950059 -0.119503
5 -0.243244 -0.014210  0.691176  0.792504
6  0.347263  0.878205  0.070437  2.126217
7  0.293059  0.271851  0.352356  0.737672
8  0.898070 -0.978699 -0.675076 -0.977196
9 -0.377312 -0.102855  1.256755  1.984360

In [111]:
# Also can "Join" and "Append" --> you can use append to add the elements of a list to the dataframe. ex if you want to add a new column 

### Setting

In [112]:
df_posA = df.copy() # Without "copy" it would act on the dataset

df_posA[df_posA.A < 0] = -1*df_posA

In [113]:
df_posA

A         B         C         D
2014-01-01  1.312591 -1.164296 -0.929280  0.230450
2014-01-02  0.849461 -0.668135 -0.565925 -1.033096
2014-01-03  0.484273  0.441717 -0.606338 -0.845852
2014-01-04  0.183280  1.296144  0.302670 -0.251709
2014-01-05  1.427229 -0.517208  0.802216 -1.636764
2014-01-06  0.844124 -1.707452 -0.449785  0.403605

In [114]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [115]:
s1

2014-01-02    1
2014-01-03    2
2014-01-04    3
2014-01-05    4
2014-01-06    5
2014-01-07    6
Freq: D, dtype: int64

In [116]:
df['F'] = s1

In [117]:
df

A         B         C         D    F
2014-01-01  1.312591 -1.164296 -0.929280  0.230450  NaN
2014-01-02  0.849461 -0.668135 -0.565925 -1.033096  1.0
2014-01-03 -0.484273 -0.441717  0.606338  0.845852  2.0
2014-01-04  0.183280  1.296144  0.302670 -0.251709  3.0
2014-01-05  1.427229 -0.517208  0.802216 -1.636764  4.0
2014-01-06  0.844124 -1.707452 -0.449785  0.403605  5.0

### Missing Data

In [118]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])

In [119]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [120]:
df1

A         B         C         D    F    E
2014-01-01  1.312591 -1.164296 -0.929280  0.230450  NaN  1.0
2014-01-02  0.849461 -0.668135 -0.565925 -1.033096  1.0  1.0
2014-01-03 -0.484273 -0.441717  0.606338  0.845852  2.0  NaN
2014-01-04  0.183280  1.296144  0.302670 -0.251709  3.0  NaN

In [121]:
# find where values are null
pd.isnull(df1)

A      B      C      D      F      E
2014-01-01  False  False  False  False   True  False
2014-01-02  False  False  False  False  False  False
2014-01-03  False  False  False  False  False   True
2014-01-04  False  False  False  False  False   True

### Applying functions

In [ ]:
df

In [ ]:
df.apply(np.cumsum)

In [ ]:
df.apply(lambda x: x.max() - x.min())

In [ ]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

### Grouping


In [122]:
df3 = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [123]:
df3

A      B         C         D
0  foo    one -1.295769 -1.907124
1  bar    one -0.686463  0.908958
2  foo    two  0.268169 -0.867206
3  bar  three  0.589382  0.825386
4  foo    two -0.763281 -1.230417
5  bar    two  0.106008 -0.512043
6  foo    one  0.717175  0.283730
7  foo  three -1.875864  0.933336

In [124]:
df3.groupby(['A','B']).sum()

C         D
A   B                        
bar one   -0.686463  0.908958
    three  0.589382  0.825386
    two    0.106008 -0.512043
foo one   -0.578594 -1.623394
    three -1.875864  0.933336
    two   -0.495112 -2.097623

In [129]:
df3.groupby(['B']).describe()

C         D
B                              
one   count  3.000000  3.000000
      mean  -0.421686 -0.238145
      std    1.032262  1.478798
      min   -1.295769 -1.907124
      25%   -0.991116 -0.811697
      50%   -0.686463  0.283730
      75%    0.015356  0.596344
      max    0.717175  0.908958
three count  2.000000  2.000000
      mean  -0.643241  0.879361
      std    1.743192  0.076332
      min   -1.875864  0.825386
      25%   -1.259552  0.852374
      50%   -0.643241  0.879361
      75%   -0.026930  0.906349
      max    0.589382  0.933336
two   count  3.000000  3.000000
      mean  -0.129701 -0.869889
      std    0.554654  0.359195
      min   -0.763281 -1.230417
      25%   -0.328636 -1.048812
      50%    0.106008 -0.867206
      75%    0.187088 -0.689625
      max    0.268169 -0.512043

### Reshaping

In [ ]:
# You can also stack or unstack levels

In [ ]:
a = df3.groupby(['A','B']).sum()

In [ ]:
# Pivot Tables
# pd.pivot_table(df3,values=['C','D'],rows=['A'],cols=['B'])

### Time Series


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [ ]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [ ]:
ts

In [ ]:
# Built in resampling
ts.resample('1Min',how='mean') # Resample secondly to 1Minutely

In [ ]:
# Many additional time series features
# ts. #use tab

### Plotting


In [ ]:
ts.plot()

In [ ]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [ ]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [ ]:
# Pandas plot function will print with labels as default

In [ ]:
df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure();df.plot();plt.legend(loc='best') #

### I/O
I/O is straightforward with, for example, pd.read_csv or df.to_csv

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/tutorials.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with examples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas